/**
 * Category catalog — drives the pSEO routes at /tiktok-shop-fees/[slug]
 * and pre-fills the calculator with category-specific defaults.
 *
 * Rates are 2026 US per TikTok Seller University. See PLAN.md §3.3.
 */

import type { WeightTier } from "./fee-engine";

export type PageIntent = "C" | "I" | "N";

export interface Category {
  slug: string;
  l1: string;
  l2: string;
  title: string;
  rate: 0.05 | 0.06;
  highTierRate?: 0.03;
  creatorBand: [number, number];
  defaults: {
    sellingPrice: number;
    cogs: number;
    creatorPct: number;
    refundRatePct: number;
  };
  weightTierDefault: WeightTier;
  intent: PageIntent;
  hookAngle: string;
  related: string[];
}

const beautyBand: [number, number] = [0.15, 0.3];
const fashionBand: [number, number] = [0.1, 0.15];
const homeBand: [number, number] = [0.12, 0.18];
const techBand: [number, number] = [0.05, 0.1];
const wellnessBand: [number, number] = [0.15, 0.25];

const _CATEGORIES: Category[] = [
  // ===== TIER 1: BEAUTY & PERSONAL CARE =====
  {
    slug: "beauty-personal-care",
    l1: "Beauty & Personal Care",
    l2: "All",
    title: "Beauty & Personal Care",
    rate: 0.06,
    creatorBand: beautyBand,
    defaults: { sellingPrice: 32, cogs: 8, creatorPct: 0.2, refundRatePct: 0.04 },
    weightTierDefault: "0-4lb",
    intent: "I",
    hookAngle:
      "Beauty is 22.5% of TikTok Shop GMV but creator commissions devour 15–30% of revenue — here's how to keep your margin.",
    related: ["skincare", "makeup", "haircare", "hyaluronic-acid-serum", "lip-products", "fragrance"],
  },
  {
    slug: "skincare",
    l1: "Beauty & Personal Care",
    l2: "Skincare",
    title: "Skincare",
    rate: 0.06,
    creatorBand: beautyBand,
    defaults: { sellingPrice: 32, cogs: 7, creatorPct: 0.2, refundRatePct: 0.04 },
    weightTierDefault: "0-4lb",
    intent: "C",
    hookAngle: "Skincare creators expect 20%+ commission. Run the math before you promise it.",
    related: ["hyaluronic-acid-serum", "brightening-serum", "face-masks", "lip-products", "haircare", "beauty-personal-care"],
  },
  {
    slug: "hyaluronic-acid-serum",
    l1: "Beauty & Personal Care",
    l2: "Skincare",
    title: "Hyaluronic Acid Serum",
    rate: 0.06,
    creatorBand: beautyBand,
    defaults: { sellingPrice: 28, cogs: 6, creatorPct: 0.22, refundRatePct: 0.03 },
    weightTierDefault: "0-4lb",
    intent: "N",
    hookAngle:
      "AM/PM routine videos drive the volume — but a 22% creator rate on $28 serum leaves you $4 before COGS.",
    related: ["skincare", "brightening-serum", "face-masks", "lash-serum", "beauty-personal-care", "lip-products"],
  },
  {
    slug: "brightening-serum",
    l1: "Beauty & Personal Care",
    l2: "Skincare",
    title: "Brightening Serum",
    rate: 0.06,
    creatorBand: beautyBand,
    defaults: { sellingPrice: 30, cogs: 7, creatorPct: 0.22, refundRatePct: 0.04 },
    weightTierDefault: "0-4lb",
    intent: "N",
    hookAngle: "Before/after content converts. The fee stack still eats 35%+ of revenue.",
    related: ["hyaluronic-acid-serum", "skincare", "face-masks", "lash-serum", "lip-products", "beauty-personal-care"],
  },
  {
    slug: "face-masks",
    l1: "Beauty & Personal Care",
    l2: "Skincare",
    title: "Face Masks",
    rate: 0.06,
    creatorBand: beautyBand,
    defaults: { sellingPrice: 18, cogs: 3, creatorPct: 0.18, refundRatePct: 0.03 },
    weightTierDefault: "0-4lb",
    intent: "N",
    hookAngle: "High repeat-purchase, low AOV — sweat the per-unit FBT math.",
    related: ["skincare", "hyaluronic-acid-serum", "brightening-serum", "bath-body", "beauty-personal-care", "haircare"],
  },
  {
    slug: "lip-products",
    l1: "Beauty & Personal Care",
    l2: "Makeup",
    title: "Lip Products",
    rate: 0.06,
    creatorBand: beautyBand,
    defaults: { sellingPrice: 16, cogs: 3, creatorPct: 0.2, refundRatePct: 0.03 },
    weightTierDefault: "0-4lb",
    intent: "N",
    hookAngle: "Lip oils exploded post-2025. Margins are tight at sub-$20 AOV.",
    related: ["makeup", "skincare", "false-lashes", "nail-polish", "beauty-personal-care", "press-on-nails"],
  },
  {
    slug: "false-lashes",
    l1: "Beauty & Personal Care",
    l2: "Makeup",
    title: "False Lashes",
    rate: 0.06,
    creatorBand: beautyBand,
    defaults: { sellingPrice: 12, cogs: 2.5, creatorPct: 0.2, refundRatePct: 0.05 },
    weightTierDefault: "0-4lb",
    intent: "N",
    hookAngle: "Classic TikTok Shop viral category. Refund rate is the killer.",
    related: ["lash-serum", "lip-products", "makeup", "press-on-nails", "nail-polish", "beauty-personal-care"],
  },
  {
    slug: "lash-serum",
    l1: "Beauty & Personal Care",
    l2: "Skincare",
    title: "Lash Serum",
    rate: 0.06,
    creatorBand: beautyBand,
    defaults: { sellingPrice: 38, cogs: 8, creatorPct: 0.22, refundRatePct: 0.04 },
    weightTierDefault: "0-4lb",
    intent: "N",
    hookAngle: "Higher AOV than lashes. Better margin if you can hold creator commission under 22%.",
    related: ["false-lashes", "hyaluronic-acid-serum", "brightening-serum", "skincare", "beauty-personal-care", "hair-growth"],
  },
  {
    slug: "nail-polish",
    l1: "Beauty & Personal Care",
    l2: "Hand, Foot & Nail Care",
    title: "Nail Polish",
    rate: 0.06,
    creatorBand: beautyBand,
    defaults: { sellingPrice: 14, cogs: 3, creatorPct: 0.18, refundRatePct: 0.03 },
    weightTierDefault: "0-4lb",
    intent: "N",
    hookAngle: "Color trends drive virality. Inventory risk is the catch.",
    related: ["press-on-nails", "lip-products", "makeup", "false-lashes", "beauty-personal-care", "skincare"],
  },
  {
    slug: "press-on-nails",
    l1: "Beauty & Personal Care",
    l2: "Hand, Foot & Nail Care",
    title: "Press-On Nails",
    rate: 0.06,
    creatorBand: beautyBand,
    defaults: { sellingPrice: 18, cogs: 4, creatorPct: 0.2, refundRatePct: 0.04 },
    weightTierDefault: "0-4lb",
    intent: "N",
    hookAngle: "Higher AOV than polish, lighter inventory than lashes.",
    related: ["nail-polish", "false-lashes", "lip-products", "makeup", "beauty-personal-care", "skincare"],
  },
  {
    slug: "makeup",
    l1: "Beauty & Personal Care",
    l2: "Makeup",
    title: "Makeup",
    rate: 0.06,
    creatorBand: beautyBand,
    defaults: { sellingPrice: 22, cogs: 5, creatorPct: 0.2, refundRatePct: 0.04 },
    weightTierDefault: "0-4lb",
    intent: "C",
    hookAngle: "L2 hub — links to lips, eyes, face.",
    related: ["lip-products", "false-lashes", "skincare", "fragrance", "beauty-personal-care", "press-on-nails"],
  },
  {
    slug: "hair-extensions",
    l1: "Beauty & Personal Care",
    l2: "Haircare & Styling",
    title: "Hair Extensions",
    rate: 0.06,
    creatorBand: beautyBand,
    defaults: { sellingPrice: 55, cogs: 14, creatorPct: 0.22, refundRatePct: 0.05 },
    weightTierDefault: "0-4lb",
    intent: "N",
    hookAngle: "Canvas Beauty did $1M in a single TikTok Live. Margins are real — if you control returns.",
    related: ["hair-growth", "haircare", "skincare", "fragrance", "beauty-personal-care", "mens-grooming"],
  },
  {
    slug: "hair-growth",
    l1: "Beauty & Personal Care",
    l2: "Haircare & Styling",
    title: "Hair Growth",
    rate: 0.06,
    creatorBand: beautyBand,
    defaults: { sellingPrice: 42, cogs: 9, creatorPct: 0.22, refundRatePct: 0.05 },
    weightTierDefault: "0-4lb",
    intent: "N",
    hookAngle: "Highest-margin sub-niche in haircare. Refund rate management is the difference.",
    related: ["haircare", "hair-extensions", "lash-serum", "skincare", "beauty-personal-care", "vitamins-supplements"],
  },
  {
    slug: "haircare",
    l1: "Beauty & Personal Care",
    l2: "Haircare & Styling",
    title: "Haircare",
    rate: 0.06,
    creatorBand: beautyBand,
    defaults: { sellingPrice: 24, cogs: 6, creatorPct: 0.2, refundRatePct: 0.04 },
    weightTierDefault: "0-4lb",
    intent: "C",
    hookAngle: "L2 hub — links to shampoo, conditioner, treatments.",
    related: ["hair-growth", "hair-extensions", "skincare", "fragrance", "beauty-personal-care", "mens-grooming"],
  },
  {
    slug: "fragrance",
    l1: "Beauty & Personal Care",
    l2: "Fragrance",
    title: "Fragrance",
    rate: 0.06,
    creatorBand: beautyBand,
    defaults: { sellingPrice: 45, cogs: 11, creatorPct: 0.18, refundRatePct: 0.03 },
    weightTierDefault: "0-4lb",
    intent: "I",
    hookAngle: "Higher AOV, lower velocity. Creator commission economics flip.",
    related: ["beauty-personal-care", "skincare", "haircare", "makeup", "bath-body", "mens-grooming"],
  },
  {
    slug: "bath-body",
    l1: "Beauty & Personal Care",
    l2: "Bath & Body Care",
    title: "Bath & Body",
    rate: 0.06,
    creatorBand: beautyBand,
    defaults: { sellingPrice: 18, cogs: 4, creatorPct: 0.18, refundRatePct: 0.03 },
    weightTierDefault: "0-4lb",
    intent: "I",
    hookAngle: "Soap and bath bombs — low margin per unit, volume game.",
    related: ["beauty-personal-care", "skincare", "fragrance", "candles", "haircare", "face-masks"],
  },
  {
    slug: "mens-grooming",
    l1: "Beauty & Personal Care",
    l2: "Men's Care",
    title: "Men's Grooming",
    rate: 0.06,
    creatorBand: beautyBand,
    defaults: { sellingPrice: 28, cogs: 6, creatorPct: 0.18, refundRatePct: 0.03 },
    weightTierDefault: "0-4lb",
    intent: "N",
    hookAngle: "Growing 2026 segment — lower creator commission expectation than women's beauty.",
    related: ["fragrance", "haircare", "hair-growth", "skincare", "beauty-personal-care", "bath-body"],
  },

  // ===== TIER 2: HEALTH & WELLNESS / SOFT LIFE =====
  {
    slug: "health-wellness",
    l1: "Health",
    l2: "All",
    title: "Health & Wellness",
    rate: 0.06,
    creatorBand: wellnessBand,
    defaults: { sellingPrice: 35, cogs: 8, creatorPct: 0.2, refundRatePct: 0.04 },
    weightTierDefault: "0-4lb",
    intent: "I",
    hookAngle: "The 'Soft Life' wave is reshaping wellness. Mid-AOV with high creator demand.",
    related: ["vitamins-supplements", "protein-powder", "weighted-plush", "red-light-therapy", "whitening-strips", "posture-correctors"],
  },
  {
    slug: "vitamins-supplements",
    l1: "Health",
    l2: "Nutrition & Wellness",
    title: "Vitamins & Supplements",
    rate: 0.06,
    creatorBand: wellnessBand,
    defaults: { sellingPrice: 32, cogs: 7, creatorPct: 0.2, refundRatePct: 0.03 },
    weightTierDefault: "0-4lb",
    intent: "C",
    hookAngle: "Subscription mentality means LTV is good. Sweat the first-order economics.",
    related: ["protein-powder", "health-wellness", "hair-growth", "weighted-plush", "skincare", "red-light-therapy"],
  },
  {
    slug: "protein-powder",
    l1: "Health",
    l2: "Nutrition & Wellness",
    title: "Protein Powder",
    rate: 0.06,
    creatorBand: wellnessBand,
    defaults: { sellingPrice: 38, cogs: 12, creatorPct: 0.18, refundRatePct: 0.03 },
    weightTierDefault: "4-10lb",
    intent: "N",
    hookAngle: "Heavier weight tier — FBT cost jumps. Bundle math matters.",
    related: ["vitamins-supplements", "health-wellness", "fitness-equipment", "activewear", "weighted-plush", "snacks"],
  },
  {
    slug: "weighted-plush",
    l1: "Toys & Hobbies",
    l2: "Dolls & Stuffed Toys",
    title: "Weighted Plush",
    rate: 0.06,
    creatorBand: wellnessBand,
    defaults: { sellingPrice: 45, cogs: 12, creatorPct: 0.2, refundRatePct: 0.04 },
    weightTierDefault: "4-10lb",
    intent: "N",
    hookAngle: "2026's breakout viral product — anxiety/insomnia angle drives conversion.",
    related: ["plush-toys", "toys-hobbies", "health-wellness", "weighted-plush", "lego-sets", "vitamins-supplements"],
  },
  {
    slug: "red-light-therapy",
    l1: "Health",
    l2: "Nutrition & Wellness",
    title: "Red Light Therapy",
    rate: 0.06,
    creatorBand: wellnessBand,
    defaults: { sellingPrice: 89, cogs: 22, creatorPct: 0.2, refundRatePct: 0.05 },
    weightTierDefault: "0-4lb",
    intent: "N",
    hookAngle: "Fastest-growing wellness sub-niche. Higher AOV absorbs creator commission.",
    related: ["health-wellness", "skincare", "vitamins-supplements", "hair-growth", "posture-correctors", "weighted-plush"],
  },
  {
    slug: "whitening-strips",
    l1: "Beauty & Personal Care",
    l2: "Nasal & Oral Care",
    title: "Whitening Strips",
    rate: 0.06,
    creatorBand: beautyBand,
    defaults: { sellingPrice: 24, cogs: 5, creatorPct: 0.2, refundRatePct: 0.03 },
    weightTierDefault: "0-4lb",
    intent: "N",
    hookAngle: "Recurring viral, low margin per unit, volume play.",
    related: ["skincare", "health-wellness", "beauty-personal-care", "hair-growth", "vitamins-supplements", "lash-serum"],
  },
  {
    slug: "posture-correctors",
    l1: "Health",
    l2: "Medical Supplies",
    title: "Posture Correctors",
    rate: 0.06,
    creatorBand: wellnessBand,
    defaults: { sellingPrice: 22, cogs: 5, creatorPct: 0.18, refundRatePct: 0.05 },
    weightTierDefault: "0-4lb",
    intent: "N",
    hookAngle: "Cheap gadget, high refund rate. Manage SPS or the return penalty doubles your cost.",
    related: ["health-wellness", "fitness-equipment", "vitamins-supplements", "red-light-therapy", "activewear", "weighted-plush"],
  },

  // ===== TIER 3: HOME, KITCHEN, ELECTRONICS =====
  {
    slug: "home-supplies",
    l1: "Home Supplies",
    l2: "All",
    title: "Home Supplies",
    rate: 0.06,
    creatorBand: homeBand,
    defaults: { sellingPrice: 28, cogs: 7, creatorPct: 0.15, refundRatePct: 0.03 },
    weightTierDefault: "0-4lb",
    intent: "I",
    hookAngle: "Practical-gadget surge — TikTok Shop's underdog category.",
    related: ["home-decor", "kitchen-gadgets", "cleaning-products", "home-organizers", "bedding", "candles"],
  },
  {
    slug: "home-decor",
    l1: "Home Supplies",
    l2: "Home Decor",
    title: "Home Decor",
    rate: 0.06,
    creatorBand: homeBand,
    defaults: { sellingPrice: 35, cogs: 9, creatorPct: 0.15, refundRatePct: 0.03 },
    weightTierDefault: "0-4lb",
    intent: "C",
    hookAngle: "Highest L2 volume in home — wall art, lights, accents.",
    related: ["home-supplies", "kitchen-gadgets", "candles", "bedding", "home-organizers", "cleaning-products"],
  },
  {
    slug: "kitchen-gadgets",
    l1: "Kitchenware",
    l2: "Kitchen Utensils & Gadgets",
    title: "Kitchen Gadgets",
    rate: 0.06,
    creatorBand: homeBand,
    defaults: { sellingPrice: 19, cogs: 4, creatorPct: 0.15, refundRatePct: 0.04 },
    weightTierDefault: "0-4lb",
    intent: "N",
    hookAngle: "Viral choppers, peelers, brushes — high refund rate is the cost of the algorithm.",
    related: ["home-supplies", "home-decor", "cleaning-products", "home-organizers", "kitchenware-hub", "bedding"],
  },
  {
    slug: "cleaning-products",
    l1: "Home Supplies",
    l2: "Home Care Supplies",
    title: "Cleaning Products",
    rate: 0.06,
    creatorBand: homeBand,
    defaults: { sellingPrice: 22, cogs: 5, creatorPct: 0.15, refundRatePct: 0.03 },
    weightTierDefault: "0-4lb",
    intent: "N",
    hookAngle: "Satisfying-content category — high conversion if you nail the demo.",
    related: ["home-supplies", "kitchen-gadgets", "home-decor", "home-organizers", "bedding", "candles"],
  },
  {
    slug: "home-organizers",
    l1: "Home Supplies",
    l2: "Home Organizers",
    title: "Home Organizers",
    rate: 0.06,
    creatorBand: homeBand,
    defaults: { sellingPrice: 26, cogs: 6, creatorPct: 0.15, refundRatePct: 0.03 },
    weightTierDefault: "0-4lb",
    intent: "C",
    hookAngle: "Closet & pantry organization — durable demand, low return rate.",
    related: ["home-supplies", "home-decor", "kitchen-gadgets", "cleaning-products", "bedding", "candles"],
  },
  {
    slug: "bedding",
    l1: "Textiles & Soft Furnishings",
    l2: "Bedding and Linens",
    title: "Bedding",
    rate: 0.06,
    creatorBand: homeBand,
    defaults: { sellingPrice: 55, cogs: 16, creatorPct: 0.15, refundRatePct: 0.04 },
    weightTierDefault: "4-10lb",
    intent: "C",
    hookAngle: "Higher AOV than most home categories. Watch FBT weight-tier cost.",
    related: ["home-decor", "home-supplies", "home-organizers", "candles", "kitchen-gadgets", "cleaning-products"],
  },
  {
    slug: "candles",
    l1: "Home Supplies",
    l2: "Home Decor",
    title: "Candles",
    rate: 0.06,
    creatorBand: homeBand,
    defaults: { sellingPrice: 22, cogs: 5, creatorPct: 0.15, refundRatePct: 0.02 },
    weightTierDefault: "0-4lb",
    intent: "N",
    hookAngle: "Mid-AOV, repeat purchase, breakage during shipping erodes margin.",
    related: ["home-decor", "home-supplies", "bedding", "bath-body", "fragrance", "home-organizers"],
  },
  {
    slug: "phones-electronics",
    l1: "Phones & Electronics",
    l2: "All",
    title: "Phones & Electronics",
    rate: 0.06,
    creatorBand: techBand,
    defaults: { sellingPrice: 45, cogs: 18, creatorPct: 0.08, refundRatePct: 0.05 },
    weightTierDefault: "0-4lb",
    intent: "I",
    hookAngle: "Tech creators take 5–10% — lowest commission band, but expect spec-heavy content.",
    related: ["phone-cases", "wireless-earbuds", "smart-home", "gaming-accessories", "home-supplies", "kitchen-gadgets"],
  },
  {
    slug: "phone-cases",
    l1: "Phones & Electronics",
    l2: "Mobile Phone Accessories",
    title: "Phone Cases",
    rate: 0.06,
    creatorBand: techBand,
    defaults: { sellingPrice: 15, cogs: 3, creatorPct: 0.08, refundRatePct: 0.04 },
    weightTierDefault: "0-4lb",
    intent: "C",
    hookAngle: "Volume play, thin margin per unit. Bundle to win.",
    related: ["phones-electronics", "wireless-earbuds", "smart-home", "gaming-accessories", "home-supplies", "press-on-nails"],
  },
  {
    slug: "wireless-earbuds",
    l1: "Phones & Electronics",
    l2: "Audio & Video",
    title: "Wireless Earbuds",
    rate: 0.06,
    creatorBand: techBand,
    defaults: { sellingPrice: 39, cogs: 14, creatorPct: 0.08, refundRatePct: 0.06 },
    weightTierDefault: "0-4lb",
    intent: "C",
    hookAngle: "High refund rate (defects, fit). SPS management is the difference.",
    related: ["phone-cases", "phones-electronics", "smart-home", "gaming-accessories", "wireless-earbuds", "home-supplies"],
  },
  {
    slug: "smart-home",
    l1: "Phones & Electronics",
    l2: "Smart & Wearable Devices",
    title: "Smart Home",
    rate: 0.06,
    creatorBand: techBand,
    defaults: { sellingPrice: 28, cogs: 10, creatorPct: 0.08, refundRatePct: 0.05 },
    weightTierDefault: "0-4lb",
    intent: "N",
    hookAngle: "Smart bulbs, plugs, sensors — Alexa/Google integration drives buyer intent.",
    related: ["phones-electronics", "wireless-earbuds", "gaming-accessories", "phone-cases", "home-supplies", "home-decor"],
  },
  {
    slug: "gaming-accessories",
    l1: "Phones & Electronics",
    l2: "Gaming & Consoles",
    title: "Gaming Accessories",
    rate: 0.06,
    creatorBand: techBand,
    defaults: { sellingPrice: 32, cogs: 11, creatorPct: 0.1, refundRatePct: 0.04 },
    weightTierDefault: "0-4lb",
    intent: "N",
    hookAngle: "Niche enthusiast audience — higher conversion, lower discount tolerance.",
    related: ["phones-electronics", "wireless-earbuds", "smart-home", "phone-cases", "lego-sets", "home-supplies"],
  },

  // ===== TIER 4: FASHION & JEWELRY (5% RATE DIFFERENTIAL) =====
  {
    slug: "womenswear",
    l1: "Womenswear & Underwear",
    l2: "All",
    title: "Womenswear",
    rate: 0.06,
    creatorBand: fashionBand,
    defaults: { sellingPrice: 38, cogs: 10, creatorPct: 0.12, refundRatePct: 0.08 },
    weightTierDefault: "0-4lb",
    intent: "I",
    hookAngle: "Fashion refund rates kill margin. Build a sizing strategy first.",
    related: ["dresses", "activewear", "dropshipping-fashion", "shoes", "fashion-accessories", "print-on-demand-tshirts"],
  },
  {
    slug: "dropshipping-fashion",
    l1: "Womenswear & Underwear",
    l2: "Women's Tops",
    title: "Dropshipping Fashion",
    rate: 0.06,
    creatorBand: fashionBand,
    defaults: { sellingPrice: 24, cogs: 7, creatorPct: 0.12, refundRatePct: 0.1 },
    weightTierDefault: "0-4lb",
    intent: "N",
    hookAngle: "High-intent commercial query. The fee stack is hostile to dropship margins.",
    related: ["womenswear", "dresses", "print-on-demand-tshirts", "fashion-accessories", "shoes", "activewear"],
  },
  {
    slug: "dresses",
    l1: "Womenswear & Underwear",
    l2: "Women's Dresses",
    title: "Dresses",
    rate: 0.06,
    creatorBand: fashionBand,
    defaults: { sellingPrice: 48, cogs: 13, creatorPct: 0.12, refundRatePct: 0.1 },
    weightTierDefault: "0-4lb",
    intent: "C",
    hookAngle: "Top womenswear L2 by GMV. Returns are the silent killer.",
    related: ["womenswear", "activewear", "dropshipping-fashion", "fashion-accessories", "shoes", "print-on-demand-tshirts"],
  },
  {
    slug: "activewear",
    l1: "Womenswear & Underwear",
    l2: "Women's Suits & Sets",
    title: "Activewear",
    rate: 0.06,
    creatorBand: fashionBand,
    defaults: { sellingPrice: 42, cogs: 11, creatorPct: 0.12, refundRatePct: 0.08 },
    weightTierDefault: "0-4lb",
    intent: "C",
    hookAngle: "'Soft Life' + wellness overlap — repeat purchase if you nail fit.",
    related: ["womenswear", "dresses", "fitness-equipment", "health-wellness", "shoes", "fashion-accessories"],
  },
  {
    slug: "print-on-demand-tshirts",
    l1: "Womenswear & Underwear",
    l2: "Women's Tops",
    title: "Print-on-Demand T-Shirts",
    rate: 0.06,
    creatorBand: fashionBand,
    defaults: { sellingPrice: 22, cogs: 9, creatorPct: 0.1, refundRatePct: 0.06 },
    weightTierDefault: "0-4lb",
    intent: "N",
    hookAngle: "POD economics — print fee is fixed, every other fee is a percentage. Math matters.",
    related: ["womenswear", "dropshipping-fashion", "dresses", "fashion-accessories", "activewear", "shoes"],
  },
  {
    slug: "shoes",
    l1: "Shoes",
    l2: "All",
    title: "Shoes",
    rate: 0.06,
    creatorBand: fashionBand,
    defaults: { sellingPrice: 52, cogs: 18, creatorPct: 0.12, refundRatePct: 0.1 },
    weightTierDefault: "0-4lb",
    intent: "I",
    hookAngle: "Sizing returns will eat you alive without a clear chart.",
    related: ["womenswear", "dresses", "fashion-accessories", "activewear", "dropshipping-fashion", "eyewear"],
  },
  {
    slug: "fashion-accessories",
    l1: "Fashion Accessories",
    l2: "All",
    title: "Fashion Accessories",
    rate: 0.06,
    creatorBand: fashionBand,
    defaults: { sellingPrice: 24, cogs: 6, creatorPct: 0.12, refundRatePct: 0.05 },
    weightTierDefault: "0-4lb",
    intent: "I",
    hookAngle: "Belts, hats, scarves — light, returnable, decent margin.",
    related: ["eyewear", "womenswear", "shoes", "silver-jewelry", "personalized-jewelry", "dresses"],
  },
  {
    slug: "eyewear",
    l1: "Fashion Accessories",
    l2: "Eyewear",
    title: "Eyewear",
    rate: 0.06,
    creatorBand: fashionBand,
    defaults: { sellingPrice: 32, cogs: 9, creatorPct: 0.12, refundRatePct: 0.07 },
    weightTierDefault: "0-4lb",
    intent: "N",
    hookAngle: "Margins surprisingly thin once you factor returns.",
    related: ["fashion-accessories", "womenswear", "shoes", "personalized-jewelry", "silver-jewelry", "activewear"],
  },
  {
    slug: "gold-jewelry",
    l1: "Jewelry Accessories & Derivatives",
    l2: "Gold",
    title: "Gold Jewelry",
    rate: 0.05,
    creatorBand: fashionBand,
    defaults: { sellingPrice: 240, cogs: 110, creatorPct: 0.1, refundRatePct: 0.02 },
    weightTierDefault: "0-4lb",
    intent: "N",
    hookAngle: "5% referral rate (not 6%) — this is the precious-jewelry discount most sellers miss.",
    related: ["silver-jewelry", "diamond-jewelry", "personalized-jewelry", "fashion-accessories", "eyewear", "womenswear"],
  },
  {
    slug: "silver-jewelry",
    l1: "Jewelry Accessories & Derivatives",
    l2: "Silver",
    title: "Silver Jewelry",
    rate: 0.06,
    creatorBand: fashionBand,
    defaults: { sellingPrice: 65, cogs: 22, creatorPct: 0.1, refundRatePct: 0.03 },
    weightTierDefault: "0-4lb",
    intent: "N",
    hookAngle: "Silver still pays the 6% rate (only gold, diamond, jade, platinum, ruby/sapphire/emerald drop to 5%).",
    related: ["gold-jewelry", "diamond-jewelry", "personalized-jewelry", "fashion-accessories", "eyewear", "womenswear"],
  },
  {
    slug: "diamond-jewelry",
    l1: "Jewelry Accessories & Derivatives",
    l2: "Diamond",
    title: "Diamond Jewelry",
    rate: 0.05,
    creatorBand: fashionBand,
    defaults: { sellingPrice: 480, cogs: 220, creatorPct: 0.08, refundRatePct: 0.02 },
    weightTierDefault: "0-4lb",
    intent: "N",
    hookAngle: "5% rate + high AOV. Capital intensity is the only friction.",
    related: ["gold-jewelry", "silver-jewelry", "personalized-jewelry", "fashion-accessories", "womenswear", "eyewear"],
  },
  {
    slug: "personalized-jewelry",
    l1: "Jewelry Accessories & Derivatives",
    l2: "Silver",
    title: "Personalized Jewelry",
    rate: 0.06,
    creatorBand: fashionBand,
    defaults: { sellingPrice: 48, cogs: 12, creatorPct: 0.12, refundRatePct: 0.03 },
    weightTierDefault: "0-4lb",
    intent: "N",
    hookAngle: "Engraved/custom items — high margin, low return rate (no resale).",
    related: ["silver-jewelry", "gold-jewelry", "diamond-jewelry", "fashion-accessories", "eyewear", "womenswear"],
  },

  // ===== TIER 5: LONG-TAIL & L1 CATCH-ALLS =====
  {
    slug: "food-beverages",
    l1: "Food & Beverages",
    l2: "All",
    title: "Food & Beverages",
    rate: 0.06,
    creatorBand: homeBand,
    defaults: { sellingPrice: 22, cogs: 6, creatorPct: 0.12, refundRatePct: 0.02 },
    weightTierDefault: "0-4lb",
    intent: "I",
    hookAngle: "Low return rate but tight margins. Subscription bundles win.",
    related: ["snacks", "coffee", "vitamins-supplements", "protein-powder", "health-wellness", "home-supplies"],
  },
  {
    slug: "snacks",
    l1: "Food & Beverages",
    l2: "Snacks",
    title: "Snacks",
    rate: 0.06,
    creatorBand: homeBand,
    defaults: { sellingPrice: 18, cogs: 5, creatorPct: 0.12, refundRatePct: 0.02 },
    weightTierDefault: "0-4lb",
    intent: "N",
    hookAngle: "Asian-snack boxes went viral in 2026 — international FBT routing matters.",
    related: ["food-beverages", "coffee", "vitamins-supplements", "protein-powder", "home-supplies", "snacks"],
  },
  {
    slug: "coffee",
    l1: "Food & Beverages",
    l2: "Drinks",
    title: "Coffee",
    rate: 0.06,
    creatorBand: homeBand,
    defaults: { sellingPrice: 24, cogs: 7, creatorPct: 0.12, refundRatePct: 0.02 },
    weightTierDefault: "0-4lb",
    intent: "C",
    hookAngle: "Specialty + instant — subscription LTV is the prize.",
    related: ["snacks", "food-beverages", "protein-powder", "vitamins-supplements", "health-wellness", "home-supplies"],
  },
  {
    slug: "pet-supplies",
    l1: "Pet Supplies",
    l2: "All",
    title: "Pet Supplies",
    rate: 0.06,
    creatorBand: homeBand,
    defaults: { sellingPrice: 22, cogs: 6, creatorPct: 0.15, refundRatePct: 0.03 },
    weightTierDefault: "0-4lb",
    intent: "I",
    hookAngle: "High repeat-purchase, emotional buyers — refund tolerance is low.",
    related: ["dog-treats", "cat-toys", "home-supplies", "vitamins-supplements", "home-decor", "snacks"],
  },
  {
    slug: "dog-treats",
    l1: "Pet Supplies",
    l2: "Dog & Cat Food",
    title: "Dog Treats",
    rate: 0.06,
    creatorBand: homeBand,
    defaults: { sellingPrice: 18, cogs: 5, creatorPct: 0.15, refundRatePct: 0.02 },
    weightTierDefault: "0-4lb",
    intent: "C",
    hookAngle: "Repeat purchase + emotional buyers = best pet-supplies sub-niche.",
    related: ["pet-supplies", "cat-toys", "snacks", "vitamins-supplements", "home-supplies", "food-beverages"],
  },
  {
    slug: "cat-toys",
    l1: "Pet Supplies",
    l2: "Dog & Cat Accessories",
    title: "Cat Toys",
    rate: 0.06,
    creatorBand: homeBand,
    defaults: { sellingPrice: 14, cogs: 3, creatorPct: 0.15, refundRatePct: 0.02 },
    weightTierDefault: "0-4lb",
    intent: "N",
    hookAngle: "Lower AOV but viral content potential is huge.",
    related: ["pet-supplies", "dog-treats", "toys-hobbies", "plush-toys", "home-supplies", "weighted-plush"],
  },
  {
    slug: "toys-hobbies",
    l1: "Toys & Hobbies",
    l2: "All",
    title: "Toys & Hobbies",
    rate: 0.06,
    creatorBand: homeBand,
    defaults: { sellingPrice: 25, cogs: 8, creatorPct: 0.15, refundRatePct: 0.03 },
    weightTierDefault: "0-4lb",
    intent: "I",
    hookAngle: "Gift-driven category — Q4 spike, summer trough.",
    related: ["plush-toys", "weighted-plush", "lego-sets", "trading-cards", "cat-toys", "home-supplies"],
  },
  {
    slug: "plush-toys",
    l1: "Toys & Hobbies",
    l2: "Dolls & Stuffed Toys",
    title: "Plush Toys",
    rate: 0.06,
    creatorBand: homeBand,
    defaults: { sellingPrice: 22, cogs: 6, creatorPct: 0.15, refundRatePct: 0.03 },
    weightTierDefault: "0-4lb",
    intent: "C",
    hookAngle: "Distinct from weighted plush — broader demand, lower AOV.",
    related: ["weighted-plush", "toys-hobbies", "cat-toys", "lego-sets", "baby-clothing", "trading-cards"],
  },
  {
    slug: "lego-sets",
    l1: "Toys & Hobbies",
    l2: "Games & Puzzles",
    title: "LEGO Sets",
    rate: 0.06,
    creatorBand: homeBand,
    defaults: { sellingPrice: 65, cogs: 28, creatorPct: 0.1, refundRatePct: 0.02 },
    weightTierDefault: "4-10lb",
    intent: "N",
    hookAngle: "Branded merchandise — thin margins but loyal buyers.",
    related: ["toys-hobbies", "plush-toys", "trading-cards", "weighted-plush", "gaming-accessories", "cat-toys"],
  },
  {
    slug: "trading-cards",
    l1: "Pre-Owned",
    l2: "Collectible Trading Cards",
    title: "Pre-Owned Trading Cards",
    rate: 0.05,
    creatorBand: homeBand,
    defaults: { sellingPrice: 45, cogs: 18, creatorPct: 0.1, refundRatePct: 0.02 },
    weightTierDefault: "0-4lb",
    intent: "N",
    hookAngle: "Pre-owned = 5% referral rate. Hits 3% on any portion over $10K per order.",
    related: ["collectibles", "lego-sets", "toys-hobbies", "plush-toys", "weighted-plush", "gaming-accessories"],
  },
  {
    slug: "collectibles",
    l1: "Collectibles",
    l2: "All",
    title: "Collectibles",
    rate: 0.06,
    highTierRate: 0.03,
    creatorBand: homeBand,
    defaults: { sellingPrice: 120, cogs: 50, creatorPct: 0.1, refundRatePct: 0.02 },
    weightTierDefault: "0-4lb",
    intent: "I",
    hookAngle: "Sub-$10K orders pay 6%; the portion above $10K drops to 3%. Big-order math matters.",
    related: ["trading-cards", "lego-sets", "toys-hobbies", "personalized-jewelry", "gold-jewelry", "plush-toys"],
  },
  {
    slug: "baby-maternity",
    l1: "Baby & Maternity",
    l2: "All",
    title: "Baby & Maternity",
    rate: 0.06,
    creatorBand: homeBand,
    defaults: { sellingPrice: 28, cogs: 7, creatorPct: 0.15, refundRatePct: 0.04 },
    weightTierDefault: "0-4lb",
    intent: "I",
    hookAngle: "Safety-conscious buyers, high return rate on fit/safety issues.",
    related: ["baby-clothing", "pet-supplies", "home-supplies", "plush-toys", "vitamins-supplements", "toys-hobbies"],
  },
  {
    slug: "baby-clothing",
    l1: "Baby & Maternity",
    l2: "Baby Clothing & Shoes",
    title: "Baby Clothing",
    rate: 0.06,
    creatorBand: homeBand,
    defaults: { sellingPrice: 22, cogs: 6, creatorPct: 0.12, refundRatePct: 0.07 },
    weightTierDefault: "0-4lb",
    intent: "C",
    hookAngle: "Sizing returns dominate. Sets sell better than singles.",
    related: ["baby-maternity", "womenswear", "plush-toys", "weighted-plush", "shoes", "fashion-accessories"],
  },
  {
    slug: "tools-hardware",
    l1: "Tools & Hardware",
    l2: "All",
    title: "Tools & Hardware",
    rate: 0.06,
    creatorBand: homeBand,
    defaults: { sellingPrice: 38, cogs: 14, creatorPct: 0.1, refundRatePct: 0.04 },
    weightTierDefault: "4-10lb",
    intent: "I",
    hookAngle: "Heavier weight tiers — FBT cost is the lever.",
    related: ["power-tools", "automotive", "car-accessories", "home-supplies", "kitchen-gadgets", "smart-home"],
  },
  {
    slug: "power-tools",
    l1: "Tools & Hardware",
    l2: "Power Tools",
    title: "Power Tools",
    rate: 0.06,
    creatorBand: homeBand,
    defaults: { sellingPrice: 89, cogs: 38, creatorPct: 0.1, refundRatePct: 0.05 },
    weightTierDefault: "4-10lb",
    intent: "C",
    hookAngle: "High AOV — absorbs creator commission well.",
    related: ["tools-hardware", "automotive", "car-accessories", "smart-home", "home-supplies", "kitchen-gadgets"],
  },
  {
    slug: "automotive",
    l1: "Automotive & Motorcycle",
    l2: "All",
    title: "Automotive",
    rate: 0.06,
    creatorBand: homeBand,
    defaults: { sellingPrice: 45, cogs: 18, creatorPct: 0.1, refundRatePct: 0.05 },
    weightTierDefault: "4-10lb",
    intent: "I",
    hookAngle: "Niche buyer base — lower creator commission expectation.",
    related: ["car-accessories", "tools-hardware", "power-tools", "smart-home", "phones-electronics", "home-supplies"],
  },
  {
    slug: "car-accessories",
    l1: "Automotive & Motorcycle",
    l2: "Car Interior Accessories",
    title: "Car Accessories",
    rate: 0.06,
    creatorBand: homeBand,
    defaults: { sellingPrice: 28, cogs: 9, creatorPct: 0.1, refundRatePct: 0.04 },
    weightTierDefault: "0-4lb",
    intent: "C",
    hookAngle: "Mid-AOV, demo-friendly content. Volume L2.",
    related: ["automotive", "tools-hardware", "power-tools", "phone-cases", "smart-home", "home-supplies"],
  },
  {
    slug: "books",
    l1: "Books, Magazines & Audio",
    l2: "All",
    title: "Books",
    rate: 0.06,
    creatorBand: fashionBand,
    defaults: { sellingPrice: 18, cogs: 8, creatorPct: 0.1, refundRatePct: 0.03 },
    weightTierDefault: "0-4lb",
    intent: "I",
    hookAngle: "BookTok works — but the fee stack on $18 paperbacks is brutal.",
    related: ["toys-hobbies", "trading-cards", "home-supplies", "baby-clothing", "weighted-plush", "lego-sets"],
  },
  {
    slug: "sports-outdoor",
    l1: "Sports & Outdoor",
    l2: "All",
    title: "Sports & Outdoor",
    rate: 0.06,
    creatorBand: homeBand,
    defaults: { sellingPrice: 42, cogs: 14, creatorPct: 0.12, refundRatePct: 0.05 },
    weightTierDefault: "4-10lb",
    intent: "I",
    hookAngle: "Seasonal, weight-tier-heavy — FBT cost is the make-or-break.",
    related: ["fitness-equipment", "activewear", "shoes", "health-wellness", "automotive", "weighted-plush"],
  },
  {
    slug: "fitness-equipment",
    l1: "Sports & Outdoor",
    l2: "Fitness",
    title: "Fitness Equipment",
    rate: 0.06,
    creatorBand: wellnessBand,
    defaults: { sellingPrice: 65, cogs: 22, creatorPct: 0.15, refundRatePct: 0.04 },
    weightTierDefault: "4-10lb",
    intent: "C",
    hookAngle: "'Soft Life' + wellness overlap. Weight tier is the trap.",
    related: ["activewear", "health-wellness", "protein-powder", "vitamins-supplements", "sports-outdoor", "red-light-therapy"],
  },
];

export const CATEGORIES: Category[] = _CATEGORIES;

export const CATEGORY_BY_SLUG: Record<string, Category> = Object.fromEntries(
  _CATEGORIES.map((c) => [c.slug, c]),
);

export function getCategory(slug: string): Category | undefined {
  return CATEGORY_BY_SLUG[slug];
}
